export type Lang = "en" | "zh";

export const copy = {
  en: {
    metaTitle: "Commit — future ASP capacity",
    metaDesc: "Reserve future capacity from participating ASPs, with clear terms for execution, fallback and settlement.",
    navReserve: "Reserve",
    navDocs: "Terms",
    navEvidence: "Evidence",
    langEn: "EN",
    langZh: "中文",
    kicker: "X Layer testnet 1952 · live HTTPS",
    h1: "Book future ASP capacity.\nPlan your next task.",
    lede: "Request a quantity. This demo assigns the next available future window. Participating providers confirm capacity and delivery terms. Review execution, failure handling and settlement when the window arrives.",
    ledeSub: "A quote is not a reservation.",
    ctaReserve: "Reserve test capacity",
    ctaEvidence: "View full evidence",
    ctaViewRun: "View a completed run",
    heroFine: "Testnet prototype · Demo primary, backup, and verifier are project-operated",
    listedKicker: "Listed on OKX AI",
    listedTitle: "Commit Capacity Quote",
    listedBody:
      "ASP #13781 is live. This is a real listed service: free quote, then occupancy + escrow on X Layer testnet. A quote is not a reservation.",
    listedFee: "0 USDT",
    listedStatus: "Listed",
    listedAsp: "ASP #13781 · Commit",
    listedServiceId: "service 8a930980-5a4b-4088-903a-82435a907865",
    pingListed: "Call listed quote",
    pinging: "Calling listed endpoint…",
    pingOk: "Listed service answered",
    pingFail: "Listed endpoint did not answer",
    statsRun: "Recorded run",
    statsRemain: "Remaining",
    statsUsed: "Used",
    statsStatus: "Status",
    openEvidence: "Evidence page",
    openCommitment: "This entitlement",
    how: "How it works",
    step1t: "Agree and reserve",
    step1: "Choose a participating service and quantity. This demo assigns the next available future window. A quote does not lock capacity; confirmation does.",
    step2t: "Execute and recover",
    step2: "Call as agreed. If terms allow, try the backup. If both miss, show the real failure.",
    step3t: "Review the record",
    step3: "Buyers check delivery and fees. Providers inspect the same execution record.",
    howMore: "8 seconds is the primary attempt deadline, not end-to-end latency. Backup retry and checkpoints add wait. Details on Docs.",
    step4t: "4. Fail over",
    step4: "8s timeout. Backup once. A late primary success does not mint extra usage.",
    step5t: "5. Transfer & settle",
    step5: "Whole remaining entitlement to a designated buyer. Then close. Standard play moves 0.59 tCOM — valueless test token.",
    trust:
      "Live testnet, not commercial mainnet. tCOM is a deliberately valueless test asset; the registry accepts a pluggable ERC-20 settlement asset. SearchNode and Nova are project-operated. The verifier is operated by Commit.",
    simTag: "30-second demo",
    simTitle: "Primary misses. Backup takes it.",
    simBody: "Illustrated product flow — not a replay of a recorded run. Watch SearchNode time out, Nova take the call, and the buyer gets the 0.02 penalty.",
    simRun: "Run demo",
    simRunning: "Running…",
    simNoWallet: "No wallet needed",
    simIllustrated: "Illustrated product flow",
    simTicket: "Bonded reserved search window",
    simQuote: "Window ready · 20 units",
    simPrimary: "SearchNode attempt",
    simTimeout: "SLA timeout · breachPrimary = 1",
    simBackup: "Nova takeover · remaining = {n}",
    simSettle: "Unit consumed · buyer compensation credited",
    simRoute: "Route",
    simPenalty: "Penalty",
    cfTag: "Capacity, not a reminder",
    cfTitle: "Two buyers. One window. Only one holds.",
    cfBody:
      "Same future slot, same inventory. Buyer A locks occupancy. Buyer B’s create returns NO_CAPACITY — a quote is not a seat.",
    cfRun: "Race the window",
    cfRunning: "Racing…",
    cfNoWallet: "Local simulation · mirrors live occupancy 409",
    cfTicket: "Provider pool · concurrency 1",
    cfWindow: "Window",
    cfPool: "Pool",
    cfResult: "Buyer B",
    cfStepQuote: "Both agents quote the same 10-minute window",
    cfStepA: "Buyer A · create → held",
    cfStepB: "Buyer B · create rejected",
    cfStepBMeta: "NO_CAPACITY · window already reserved",
    cfStepWhy: "Inventory is the product. A quote is not a lock.",
    audienceTitle: "Who reserves capacity",
    audience1T: "Agent frameworks",
    audience1: "Guarantee a tool call window before an autonomous workflow starts.",
    audience2T: "Data providers",
    audience2: "Pre-sell bounded query capacity with explicit SLA and bonded backup.",
    audience3T: "Secondary buyers",
    audience3: "Acquire the whole remaining entitlement when demand or ownership changes.",
    reserveTag: "Quote ≠ reserved",
    reserveH1: "Reserve search capacity",
    reserveLede:
      "This form calls the listed OKX AI service Commit Capacity Quote (#13781), then holds occupancy and can create on the 1952 registry. Concurrency 1, 1s spacing, 8s attempt timeout, two attempts.",
    reserveWindowNote:
      "This demo assigns the next available future window automatically. After a quote, confirm the start and end times before reserving.",
    serviceClass: "Service class",
    quantity: "Quantity (max 20)",
    getQuote: "Get listed quote",
    quoting: "Quoting…",
    next: "Next: occupancy hold, then wallet sign-in, then create on the registry.",
    signReserve: "Sign in and reserve",
    reserveApprove: "One action starts the flow. Commit submits the exact tCOM allowance, waits for confirmation, then creates the registry commitment.",
    localDemo: "Local Hardhat session",
    window: "Window",
    docsH1: "Scope, terms, trust limits",
    docsWhatT: "What this is",
    docsWhat:
      "Commit is future service reservations and delivery commitments for participating ASPs: window, quantity, execution terms, fallback, and settlement. It is not an agent storefront and not a general search engine.",
    docsNetT: "Networks",
    docsNet:
      "The public host commit.jibai.site is live on X Layer testnet chainId 1952 with deployed tCOM and registry. Local reproduction boots Hardhat 31337. Mainnet 196 is disabled.",
    docsAssetT: "Asset",
    docsAsset: "tCOM is a deliberately valueless, 6-decimal test asset—not the product. The registry is designed around a pluggable ERC-20 settlement asset. Standard play: 20 × 0.01 + 0.02 + 0.02 = buyer total 0.24; bonds 0.10 each; penalty 0.02. Conserved local T30 (run-specific) is 0.59 including transfer.",
    docsProvT: "Providers",
    docsProv:
      "SearchNode (primary) and Nova (backup) are project-operated HTTP services over a fixed public corpus. They may share a host. That is disclosed, not independent disaster recovery.",
    docsVerT: "Verifier",
    docsVer:
      "Checkpoints are signed by a Commit-operated verifier. A dishonest verifier can mis-report; bonds cap cash damage, they do not create unfailing service.",
    docsRoadmapT: "Verifier decentralisation roadmap",
    docsRoadmap: "Phase 1 (now): one disclosed Commit signer and fully reproducible evidence. Phase 2: independent 2-of-3 attestations with signer rotation and public liveness metrics. Phase 3: permissionless verifier staking, challenge windows, and slashing for conflicting checkpoints. Contract signatures and evidence hashes are the migration hooks; no claim of decentralisation is made today.",
    docsOkxT: "OKX AI",
    docsOkx:
      "The product you reserve here is the listed service Commit Capacity Quote on ASP #13781. Execution still runs on Commit’s bonded SearchNode / Nova pair — not a catalog of every marketplace agent.",
    docsReproT: "Reproduce locally",
    evTag: "Recorded run · not a live dashboard",
    evHeadHeldFailover: "Recorded failover run",
    evHeadClosed: "Closed on-chain · settlement not completed",
    evHeadListed: "Recorded transfer listing run",
    evHeadTransferred: "Recorded ownership transfer run",
    evHeadSettled: "Completed and settled run",
    evHeadFailed: "Recorded failed run",
    evHeldDisclaimer: "Failover proof only; not a full settlement play. Held · not settled.",
    evClosedDisclaimer:
      "On-chain status 1 is CLOSED (0 OPEN, 1 CLOSED, 2 SETTLED). Occupancy can still read held or expired if settle() was not recorded.",
    evSettleIncomplete:
      "closeWithCheckpoint later read as CLOSED. A later prepare-close retried close and reverted NotClosable (0x74c77f3b), so settle() was not submitted. Occupancy is not SETTLED. This page does not invent a settle transaction.",
    evRecordedNote: "This page is a recorded snapshot. Wallet claimable totals below are across all test runs on this registry, not this commitment alone.",
    evH1: "Evidence",
    evLatest: "(latest on this host)",
    evLede: "A recorded run, already written. Check transactions on the explorer. tCOM has no value.",
    evWhat: "What happened",
    evRemain: "Remaining",
    evUsed: "Used",
    evStatus: "Status",
    evPrimary: "Primary",
    evFail: "Failover",
    evNoInject: " (fault inject missed that day)",
    evAfter: "After transfer",
    evOpen: "Open entitlement",
    evTx: "Open create tx on X Layer testnet",
    evTermsT: "Terms integrity",
    evQuoteHash: "Quoted termsHash",
    evChainHash: "On-chain termsHash",
    evTermsMatch: "Exact match",
    evTermsUnavailable: "Awaiting both quote and chain hashes",
    evLoading: "Loading record…",
    loadingCommitment: "Loading commitment…",
    missingCommitment: "That entitlement is not in this API ledger. Open the latest recorded run:",
    // status chip
    apiOk: "API live",
    apiDown: "API unreachable",
    chain: "chain",
    // ticket
    ticketTitle: "What you lock",
    ticketWindow: "Window",
    ticketWindowV: "10 min from quote",
    ticketQty: "Quantity",
    ticketQtyV: "up to 20 search.v1 calls",
    ticketSla: "SLA",
    ticketSlaV: "8 s attempt · backup once",
    ticketProviders: "Providers",
    ticketProvidersV: "SearchNode + Nova",
    ticketBond: "Bonds",
    ticketBondV: "0.10 tCOM each · 0.02 / miss",
    ticketBuyer: "Buyer total (20 units)",
    ticketBuyerV: "0.24 tCOM in escrow",
    ticketAsset: "Asset",
    ticketAssetV: "tCOM · 6 decimals · no value",
    ticketFoot: "search.v1 · testnet only",
    // trust strip
    trustVerifiedToken: "tCOM verified",
    trustVerifiedRegistry: "Registry verified",
    trustListed: "Listed ASP #13781",
    trustChain: "X Layer testnet 1952",
    trustSourcify: "Sourcify exact match",
    // compare
    compareTitle: "Cron / spot call vs. Commit window",
    compareSpot: "Cron + spot call",
    compareCommit: "Commit window",
    cmp1k: "What you buy",
    cmp1a: "A reminder to ask later",
    cmp1b: "Quantity + time window + SLA, forward",
    cmp2k: "If the provider misses",
    cmp2a: "Retry and hope",
    cmp2b: "Bonded backup takes the call; primary is penalised",
    cmp3k: "Unused capacity",
    cmp3a: "Gone",
    cmp3b: "Transferable entitlement (whole remaining)",
    cmp4k: "Two buyers, one slot",
    cmp4a: "Both fire; whoever the API likes",
    cmp4b: "Second create → NO_CAPACITY",
    cmp5k: "Proof",
    cmp5a: "A chat log / cron log",
    cmp5b: "Signed checkpoints + on-chain settlement",
    evEconT: "This-run counters",
    evThisRunT: "This commitment (on-chain counters)",
    evThisRunNote: "Breach and success counts for this commitment only. Do not treat wallet claimable as this-run P&L.",
    evWalletT: "Wallet-level balances across all test runs",
    evWalletNote: "claimable[address] is cumulative on this registry. Not this-run economics.",
    evEconBuyer: "Buyer claimable (wallet)",
    evEconPrimary: "Primary claimable (wallet)",
    evEconBackup: "Backup claimable (wallet)",
    evEconBreach: "Breaches",
    evEconRoute: "Request route",
    evEconNote: "Amounts in tCOM (6 decimals).",
    docsTableT: "Current testnet standard terms",
    docsRowNetwork: "Network",
    docsRowAsset: "Asset",
    docsRowQty: "Quantity",
    docsRowUnit: "Unit price",
    docsRowFees: "Reservation fees",
    docsRowBond: "Primary/backup bond",
    docsRowDeadline: "Attempt deadline",
    docsRowAttempts: "Maximum attempts",
    docsRowPenalty: "Penalty",
    docsRowTransfer: "Transfer",
    docsRowVerifier: "Verifier",
    docsValNetwork: "X Layer Testnet 1952",
    docsValAsset: "tCOM, no value",
    docsValQty: "20 units",
    docsValUnit: "0.01 tCOM",
    docsValFees: "0.02 + 0.02 tCOM (buyer total 0.24)",
    docsValBond: "0.10 tCOM each",
    docsValDeadline: "8 seconds per attempt (not end-to-end)",
    docsValAttempts: "2",
    docsValPenalty: "0.02 tCOM / bonded miss",
    docsValTransfer: "whole remaining entitlement only",
    docsValVerifier: "Commit-operated",
    cmEconT: "Claimable (live chain)",
    // providers
    providersTitle: "Bonded providers behind every window",
    provPrimary: "Primary",
    provBackup: "Backup",
    provBond: "Bond",
    provRole1: "Answers first. 8 s to respond or the attempt is charged to it.",
    provRole2: "Takes the call once when the primary misses. Never retried silently.",
    provDisclosure: "Both are project-operated Search v1 services over a fixed public corpus. Disclosed, not third-party SaaS.",
    // evidence timeline
    tlTitle: "Timeline of this run",
    tlQuote: "Quote from listed service",
    tlReserve: "Occupancy held · escrow + bonds created on 1952",
    tlPrimary: "Primary execution",
    tlFailover: "Fault injected → backup took the call",
    tlFaultMissed: "Second call · fault injection missed, primary served (no failover in this run)",
    tlTransfer: "Whole remaining entitlement transferred",
    tlAfter: "New owner executed",
    tlClose: "Closed and settled",
    tlNotRun: "Not run",
    tlRaw: "Raw record (JSON)",
    // commitments page
    cmOwner: "Owner",
    cmRemaining: "remaining",
    cmUsed: "used",
    cmRoute: "route",
    cmExec: "Execute search.v1",
    cmQuery: "Query",
    cmRun: "Run attempt",
    cmReq: "Request",
    cmStatus: "Status",
    cmTransferT: "Transfer remaining entitlement",
    cmTransferP: "Whole remaining only. In-flight requests must drain first.",
    cmBuyer: "Designated buyer",
    cmFreeze: "Freeze and list",
    cmOpenListing: "Open listing",
    cmClose: "Close and settle",
    cmChainPending: "chain pending",
    cmOpenExplorer: "Open create tx on explorer",
    // transfers page
    trTag: "Whole remaining entitlement",
    trH1: "Buy this window",
    trP: "You receive remaining units, the leftover window, and the SLA — not a chatbot account.",
    trSeller: "Seller",
    trBuyer: "Designated buyer",
    trRemaining: "Remaining",
    trPrice: "Price",
    trStatus: "Status",
    trBuy: "Buy as designated buyer",
    trView: "View commitment",
    trDone: "Purchased. Owner epoch advanced. Execute from the new wallet only.",
    trLoading: "Loading listing…",
    // footer
    footContracts: "Contracts (X Layer testnet 1952)",
    footToken: "tCOM · MockToken",
    footRegistry: "CommitmentRegistry",
    footAsp: "OKX AI listing",
    footExplorer: "Explorer",
    footSourcify: "Sourcify",
    footLine:
      "tCOM has no value. Primary, backup, and verifier are operated by Commit. Fixed corpus. Not a commercial mainnet service.",
    copyAddress: "Copy address",
    copy: "Copy",
    copied: "Copied",
    navAgent: "Agent",
    navLab: "Capacity",
    evResultT: "This run at a glance",
    evResultReq: "Requests",
    evResultFail: "Failovers",
    evResultXfer: "Transfers",
    evResultSettle: "Settled",
    evEconThisT: "This commitment — fees, compensation, refund",
    evEconPrepaid: "Buyer prepaid",
    evEconPay: "Paid to providers (used × 0.01)",
    evEconRefund: "Unused escrow refunded",
    evEconPenalty: "Failover penalty to owner",
    evEconXfer: "Transfer payment",
    evEconConserved: "Used + unused = original execution escrow",
    evT30T: "Isolated T30 vs shared registry",
    evT30Na: "The stored ok:false compares wallet-level claimable to an isolated Hardhat 0.59 check. That check does not apply to this shared 1952 registry. It is not a funds-loss.",
    evCallT: "OKX AI → on-chain trail",
    evExplorer: "Explorer",
    evWalletDetails: "Wallet-level totals and raw JSON",
    reserveExpiry: "Quote expires",
    reserveAttempt: "8 s is the primary attempt timeout. Failover and settlement take longer.",
    reserveTz: "Times in UTC",
    reserveFees: "Buyer total",
    agentTag: "Recorded example · Project-operated services · X Layer testnet",
    agentH1: "How one search handled a primary timeout",
    agentLede: "An agent reserved search capacity through the listed OKX AI quote, used the window, and continued after SearchNode missed 8 s. SearchNode and Nova are project-operated. This is not a research report.",
    agentBriefT: "Recorded execution summary",
    agentTrailT: "Call chain",
    agentLimit: "SearchNode and Nova are project-operated over a fixed corpus. This is one example agent, not a marketplace of agents.",
    agentBody: "Queries and statuses below come from the recorded run. Remaining units were transferable; unused escrow returned at settle. No delivery-time claim is made here.",
    navCode: "Developers",
    navHow: "How it works",
    navDemo: "Demo",
    sceneT: "A search task reserved capacity before it needed the call.",
    sceneP: "It reserved a future search window, then used it. This example shows how one primary timeout was handled.",
    sceneSee: "See the case. Then check the proof.",
    sceneArt: "Concept only: a reserved backup path. Not an execution diagram.",
    runProofP: "The record links requests to testnet transactions. The verifier is project-operated; on-chain data does not independently prove that the off-chain service occurred.",
    labHomeLink: "Capacity race — controlled occupancy lab",
    okxLine: "Discover and quote through OKX AI. Record the commitment and settlement on X Layer testnet.",
    footTech: "Built with OKX AI + X Layer testnet",
    labTag: "Capacity lab",
    labH1: "How capacity avoids oversell",
    labLede: "Reservation locks both provider pools for that window. A later overlapping quote is NO_CAPACITY — execute is not an open queue. This button runs a live API occupancy hold on a far-future 10-minute slot (expires in ~120 s). It does not send a 1952 transaction.",
    labRun: "Run live occupancy race",
    labRunning: "Racing…",
    labA: "Agent A",
    labB: "Agent B",
    labExec: "Execute without a reservation",
    labNote: "Controlled lab. Not paying customers. Not an independent provider network.",
    docsAttemptNote: "The 8-second figure is the primary attempt deadline. A backup attempt, outbox checkpoint, and user wait can exceed 8 seconds. Settlement is not instant.",
    docsAssetNote: "The registry accepts a pluggable ERC-20 settlement asset. tCOM is the current test token and has no value.",
    footAgent: "Agent example",
    footLab: "Capacity race",
    footVideo: "Demo video not published yet",
    labOversell: "Oversell",
    labWindow: "Lab window",
    ctaHow: "See how it works",
    ctaDemo: "View demo",
    howScene: "Agree, execute, review.",
    howSub: "A quote does not lock capacity. Confirmation starts the reservation.",
    previewKicker: "Recorded example",
    ctaRecorded: "View full evidence →",
    navProviders: "For providers",
    kickerAsp: "Future service reservations for AI agents",
    aspExpand: "ASP means Agent Service Provider — a vendor of search, data, or similar capabilities.",
    problemT: "After a service is listed, delivery is the hard part.",
    problemP:
      "Commit comes from operating an ASP. For a buyer, one timeout can stop the next step. For a provider, without a capacity commitment and a delivery record, it is hard to see what to fix.",
    buyerColT: "Buyers",
    buyerColP: "When can I use it? How much? What happens if it fails?",
    provColT: "Providers",
    provColP: "How much should I promise? Where did I miss? How do I show my record?",
    caseT: "How one search task handled a primary timeout.",
    casePromise: "Promised",
    caseActual: "What ran",
    caseHandling: "How it was handled",
    casePromiseV: "20 search units · 8 s primary attempt · bonded backup",
    caseActualV: "3 executed · 1 primary timeout · backup returned",
    caseHandlingV: "Remaining units transferred, then settled. Unused escrow returned.",
    provSecT: "Make reliable delivery a provider record.",
    provSecP: "Demo sample from one testnet run. Not a production rating or long-run stability claim.",
    provHit: "On-time primary returns",
    provBackupM: "Backup recoveries",
    provFailN: "Both paths failed",
    provInject: "Controlled fault inject — not used for production rating.",
    provCap: "State capacity you can actually hold.",
    provSee: "See where a miss happened.",
    provTune: "Use the record to adjust capacity and configuration. That loop is supported; it is not claimed as already improved uptime.",
    ecoT: "Where each layer sits",
    ecoOkx: "OKX AI — discovery and listed quote",
    ecoCommit: "Commit — terms, reservation, execution management",
    ecoAsp: "Participating ASP — the actual service",
    ecoXlayer: "X Layer — terms hash, escrow rules, settlement",
    ecoVerifier: "The verifier observes off-chain execution and submits checkpoints. Currently project-operated.",
    agentTaskT: "What was asked",
    agentReservedT: "What was reserved",
    agentGotT: "What came back",
    agentHappenedT: "What happened",
    agentMoneyT: "How money moved",
    agentNoOutput: "Response bodies were not stored. Only schema checks and a response hash remain. This page does not invent search snippets.",
    loadWait: "Loading the recorded example…",
    loadFail: "Could not load the record.",
    notRecorded: "Not recorded",
    retry: "Retry",
    labDiagramT: "Diagram — local simulation, no database, no chain transaction",
    labApiT: "Controlled API experiment — temporary hold, ~120 s TTL, no 1952 transaction",
    evFeeReserveSplit: "Reservation fees {fees} tCOM, split primary / backup",
    evFeeIdentity: "{prepaid} = {fees} reservation + {pay} execution + {refund} unused",
    evFeeBond: "{penalty} compensation comes from the primary bond, not execution escrow",
    evFeeXferNote: "{xfer} transfer is a separate payment from the new buyer to the previous owner",
    evClaimableNote: "claimable is not a completed withdrawal",
    evFirstT: "This commitment",
    evFirstService: "Service",
    evFirstOp: "Operator",
    evFirstWindow: "Window",
    evFirstResult: "Result",
    evFirstMoney: "Funds",
    evFirstVerify: "Verification",
    serviceOp: "Project-operated SearchNode / Nova",
    settledYes: "yes",
    settledNo: "no",
    adapterNav: "Provider contract",
    adapterTag: "Integration shape · not a self-serve marketplace",
    adapterH1: "How a participating ASP plugs in",
    adapterLede:
      "Commit can point at a service that speaks this contract. There is no self-serve registry. An operator configures the URL. Occupancy is admission for a reserved window, not a lock on the upstream’s machines.",
    adapterShapeT: "Execute contract",
    adapterShape:
      "POST {base}/execute with JSON { attemptId, query }. Respond within the attempt deadline (demo: 8 seconds). Body must be search.v1: schemaVersion, query, providerId, requestId, results[] (title, sourceUrl, snippet, recordId). Wrap it as { status, providerId, response } the way the demo providers do.",
    adapterLimitT: "What Commit actually locks",
    adapterLimit:
      "Quote does not reserve. Confirmation holds both primary and backup pools for that window. Execute is rejected without a hold. Bonds, escrow, backup-once, and settlement follow the quoted terms. Commit does not reserve CPU, quota, or inventory inside the upstream ASP.",
    adapterNotT: "Not included",
    adapterNot:
      "No provider signup, no ranking, no automatic failover to an arbitrary listed ASP. Backup must be an explicitly compatible search.v1 service. Trading or other side-effecting APIs are out of scope.",
    adapterExT: "Adapter example",
    adapterExP: "About fifty lines: wrap any read-only JSON HTTP API. File in the repo: packages/provider-sdk/examples/readonly-http-adapter.mjs",
    caseProtocolT: "Protocol evidence",
    caseProtocolP:
      "Separate recorded run: primary timeout, backup, transfer, settle. Response bodies were not stored on that run. Not spliced with the delivery example.",
    caseDeliveryT: "Delivery example",
    caseDeliveryP:
      "Separate recorded run after body persistence. Stored search.v1 hits from the fixed public corpus. 3 units used. Close/settle was not completed on this run. Not a live web search. Not spliced with the protocol run.",
    agentCorpus: "Fixed public corpus · project-operated SearchNode / Nova",
    agentHitSource: "Source",
    docsAdapterT: "Provider contract",
    docsAdapter:
      "A participating search service can speak POST /execute + search.v1. Commit occupancy is admission, not upstream capacity. This is a configured plug, not self-serve onboarding.",
    docsSourceT: "Source repository",
    docsSourcePending: "Source repository is not published yet.",
    docsVideoT: "Demo video",
  },
  zh: {
    metaTitle: "Commit — 预约 ASP 未来服务",
    metaDesc: "现在预约接入 ASP 的未来服务容量，让到时的执行、失败处理和结算都有明确约定。",
    navReserve: "预订",
    navDocs: "条款",
    navEvidence: "证据",
    langEn: "EN",
    langZh: "中文",
    kicker: "X Layer 测试网 1952 · 实盘 HTTPS",
    h1: "提前预约 ASP 服务，\n让未来任务有所准备。",
    lede: "填写调用次数即可。当前演示自动分配下一个可用的未来窗口。由接入的服务商确认容量和交付条款。到时按约执行，失败按条款处理，留下可核查的履约与结算记录。",
    ledeSub: "报价不等于已预订。",
    ctaReserve: "预订测试容量",
    ctaEvidence: "查看完整凭证",
    ctaViewRun: "查看一次完整履约",
    heroFine: "测试网原型 · 当前演示的主备服务与验证者由项目方运营",
    listedKicker: "已在 OKX AI 上架",
    listedTitle: "Commit Capacity Quote",
    listedBody: "ASP #13781 已上架。这是真实上架服务：报价免费，然后在 X Layer 测试网占用并托管。报价不等于已预订。",
    listedFee: "0 USDT",
    listedStatus: "已上架",
    listedAsp: "ASP #13781 · Commit",
    listedServiceId: "服务 8a930980-5a4b-4088-903a-82435a907865",
    pingListed: "调用已上架报价",
    pinging: "正在调用已上架接口…",
    pingOk: "已上架服务已应答",
    pingFail: "已上架接口无应答",
    statsRun: "已记录履约",
    statsRemain: "剩余",
    statsUsed: "已用",
    statsStatus: "状态",
    openEvidence: "证据页",
    openCommitment: "这笔权益",
    how: "原理",
    step1t: "约定并预订",
    step1: "选择已接入服务和数量。当前演示自动分配下一个可用的未来窗口。报价不锁容量，确认后才预订。",
    step2t: "执行与补救",
    step2: "按约定调用。符合条件时切换备用；两者失败则显示真实失败。",
    step3t: "核对履约记录",
    step3: "买方核对交付与费用，供应商查看同一份执行记录。",
    howMore: "8 秒是主路单次尝试期限，不是端到端时延。备用重试和检查点会再花时间。细节见条款页。",
    step4t: "4. 故障切换",
    step4: "8 秒超时。备用一次。迟到的主路成功不会再扣一次用量。",
    step5t: "5. 转让与结算",
    step5: "剩余权益整笔转给指定买家，然后关闭。标准剧本划转 0.59 tCOM——无价值测试代币。",
    trust:
      "测试网实盘，不是主网商业盘。tCOM 是刻意无价值的测试资产；登记合约支持可插拔 ERC-20 结算资产。SearchNode / Nova 为项目自营，验证器由 Commit 运营。",
    simTag: "30 秒演示",
    simTitle: "主路失约，备用接手。",
    simBody: "产品流程示意——不是某笔 recorded run 的回放。看 SearchNode 超时、Nova 接走调用，买方拿到 0.02 扣罚补偿。",
    simRun: "播放演示",
    simRunning: "播放中…",
    simNoWallet: "无需钱包",
    simIllustrated: "产品流程示意",
    simTicket: "交保证金的预订搜索窗口",
    simQuote: "窗口就绪 · 20 单位",
    simPrimary: "SearchNode 尝试",
    simTimeout: "SLA 超时 · breachPrimary = 1",
    simBackup: "Nova 接手 · remaining = {n}",
    simSettle: "消耗 1 单位 · 买方补偿到账",
    simRoute: "路由",
    simPenalty: "扣罚",
    cfTag: "容量，不是提醒",
    cfTitle: "两个买家，一个窗口，只能锁一家。",
    cfBody: "同一未来时段、同一库存。买家 A 占住占用。买家 B 的 create 返回 NO_CAPACITY——报价不是座位。",
    cfRun: "竞抢同一窗口",
    cfRunning: "竞抢中…",
    cfNoWallet: "本地模拟 · 与线上占用 409 一致",
    cfTicket: "服务商池 · 并发 1",
    cfWindow: "窗口",
    cfPool: "库存",
    cfResult: "买家 B",
    cfStepQuote: "两边对同一 10 分钟窗口报价",
    cfStepA: "买家 A · create → held",
    cfStepB: "买家 B · create 被拒",
    cfStepBMeta: "NO_CAPACITY · 窗口已被预订",
    cfStepWhy: "产品是库存。报价不是锁。",
    audienceTitle: "谁会预订容量",
    audience1T: "Agent 框架",
    audience1: "在自主工作流开始前，为工具调用锁定有保证的时间窗。",
    audience2T: "数据服务商",
    audience2: "预售有上限的查询容量，明确 SLA，并由保证金备用服务托底。",
    audience3T: "二级买家",
    audience3: "需求或所有权变化时，买下整笔剩余权益。",
    reserveTag: "报价 ≠ 已预订",
    reserveH1: "预订搜索容量",
    reserveLede:
      "此表单调用 OKX AI 已上架服务 Commit Capacity Quote（#13781），再占用库存，并可在 1952 登记合约上创建。并发 1、间隔 1 秒、尝试超时 8 秒、最多两次。",
    reserveWindowNote: "当前演示自动分配下一个可用的未来窗口；报价后请确认开始和结束时间。",
    serviceClass: "服务类别",
    quantity: "数量（最多 20）",
    getQuote: "取上架报价",
    quoting: "报价中…",
    next: "下一步：先占用库存，再用钱包签名，在登记合约上创建。",
    signReserve: "钱包登录并预订",
    reserveApprove: "一次操作启动流程：Commit 提交精确的 tCOM 授权额度，等待确认后创建登记权益。",
    localDemo: "本机 Hardhat 会话",
    window: "窗口",
    docsH1: "范围、条款、信任边界",
    docsWhatT: "这是什么",
    docsWhat: "Commit 是接入 ASP 的未来服务预约与履约管理：时间窗、数量、执行条款、失败处理与结算。它不是 Agent 店面，也不是通用搜索引擎。",
    docsNetT: "网络",
    docsNet:
      "公网站 commit.jibai.site 跑在 X Layer 测试网 chainId 1952，tCOM 和登记合约已部署。本机复现才启动 Hardhat 31337。主网 196 已禁用。",
    docsAssetT: "资产",
    docsAsset: "tCOM 是刻意无价值的 6 位测试资产，不是产品本身。登记合约按可插拔 ERC-20 结算资产设计。标准剧本：20 × 0.01 + 0.02 + 0.02 = 买方合计 0.24；保证金各 0.10；扣罚 0.02。本机 T30 守恒总额 0.59（含转让，属该次 run）。",
    docsProvT: "服务商",
    docsProv:
      "SearchNode（主）和 Nova（备）是项目自营 HTTP 服务，固定公开语料。它们可能同机。这是披露，不是独立灾备。",
    docsVerT: "验证器",
    docsVer: "检查点由 Commit 运营的验证器签名。不诚实的验证器可能误报；保证金封顶资金损失，不能保证服务永不失败。",
    docsRoadmapT: "验证器去中心化路线图",
    docsRoadmap: "阶段 1（当前）：单个、已披露的 Commit 签名者，证据可完整复现。阶段 2：独立 2/3 多方证明、签名者轮换与公开活性指标。阶段 3：无许可验证器质押、挑战窗口，并对冲突检查点罚没。合约签名与证据哈希已作为迁移挂钩；今天不宣称去中心化。",
    docsOkxT: "OKX AI",
    docsOkx:
      "你在这里预订的产品，就是 ASP #13781 上已上架的 Commit Capacity Quote。履约仍跑在 Commit 交了保证金的 SearchNode / Nova 上——不是全市场所有 Agent 的目录。",
    docsReproT: "本机复现",
    evTag: "已记录履约 · 不是实时看板",
    evHeadHeldFailover: "已记录故障切换",
    evHeadClosed: "链上已关闭 · 未完成结算",
    evHeadListed: "已记录转让挂牌",
    evHeadTransferred: "已记录所有权转让",
    evHeadSettled: "已完成并结算",
    evHeadFailed: "已记录失败履约",
    evHeldDisclaimer: "仅证明故障切换；不是完整结算剧本。Held · 未结算。",
    evClosedDisclaimer:
      "链上 status 1 为 CLOSED（0 OPEN、1 CLOSED、2 SETTLED）。若 settle() 未落库，占用接口仍可能显示 held 或 expired。",
    evSettleIncomplete:
      "closeWithCheckpoint 之后链上读到 CLOSED。后续 prepare-close 再次调用 close，因已关闭而回退 NotClosable（0x74c77f3b），因此没有提交 settle()。占用状态不是 SETTLED。本页不编造结算交易。",
    evRecordedNote: "本页是已落库快照。下方钱包可领金额是本登记合约上所有测试运行的累计，不是这一笔 commitment 单独的盈亏。",
    evH1: "证据",
    evLatest: "（本站最新一笔）",
    evLede: "已经落库的履约记录。链上交易可在浏览器核对。tCOM 无价值。",
    evWhat: "这一笔发生了什么",
    evRemain: "剩余",
    evUsed: "已用",
    evStatus: "状态",
    evPrimary: "主路",
    evFail: "故障切换",
    evNoInject: "（当时故障注入未生效）",
    evAfter: "转让后执行",
    evOpen: "打开权益",
    evTx: "在 X Layer 测试网浏览器打开创建交易",
    evTermsT: "条款完整性",
    evQuoteHash: "报价 termsHash",
    evChainHash: "链上 termsHash",
    evTermsMatch: "完全匹配",
    evTermsUnavailable: "等待报价与链上哈希齐备",
    evLoading: "正在读取记录…",
    loadingCommitment: "正在读取权益…",
    missingCommitment: "这笔权益不在本 API 账本。打开最近一笔已记录履约：",
    apiOk: "API 在线",
    apiDown: "API 不可达",
    chain: "链",
    ticketTitle: "你锁定的内容",
    ticketWindow: "窗口",
    ticketWindowV: "报价起 10 分钟",
    ticketQty: "数量",
    ticketQtyV: "最多 20 次 search.v1",
    ticketSla: "SLA",
    ticketSlaV: "8 秒尝试 · 备用一次",
    ticketProviders: "服务商",
    ticketProvidersV: "SearchNode + Nova",
    ticketBond: "保证金",
    ticketBondV: "各 0.10 · 失约扣 0.02",
    ticketBuyer: "买方合计（20 单位）",
    ticketBuyerV: "0.24 tCOM · 托管在登记合约",
    ticketAsset: "资产",
    ticketAssetV: "tCOM · 6 位小数 · 无价值",
    ticketFoot: "search.v1 · 仅测试网",
    trustVerifiedToken: "tCOM 已开源验证",
    trustVerifiedRegistry: "登记合约已开源验证",
    trustListed: "已上架 ASP #13781",
    trustChain: "X Layer 测试网 1952",
    trustSourcify: "Sourcify 精确匹配",
    compareTitle: "定时 / 现货调用 vs. Commit 窗口",
    compareSpot: "定时任务 + 现货调用",
    compareCommit: "Commit 窗口",
    cmp1k: "你买到的",
    cmp1a: "到点提醒自己去问",
    cmp1b: "数量 + 时间窗 + SLA，远期锁定",
    cmp2k: "服务商失约时",
    cmp2a: "重试，看运气",
    cmp2b: "交了保证金的备用接手；主路被扣罚",
    cmp3k: "未用完的容量",
    cmp3a: "作废",
    cmp3b: "可整笔转让的权益",
    cmp4k: "两个买家抢同一时段",
    cmp4a: "两边都打；看接口心情",
    cmp4b: "第二个 create → NO_CAPACITY",
    cmp5k: "凭证",
    cmp5a: "聊天记录 / cron 日志",
    cmp5b: "签名检查点 + 链上结算",
    evEconT: "本笔计数",
    evThisRunT: "本 commitment（链上计数）",
    evThisRunNote: "仅本 commitment 的违约/成功计数。不要把钱包可领当成这一笔的盈亏。",
    evWalletT: "钱包级累计（本登记合约上所有测试运行）",
    evWalletNote: "claimable[address] 是跨 commitment 累计。不是本笔经济结果。",
    evEconBuyer: "买方可领（钱包累计）",
    evEconPrimary: "主路可领（钱包累计）",
    evEconBackup: "备路可领（钱包累计）",
    evEconBreach: "违约计数",
    evEconRoute: "请求路径",
    evEconNote: "金额单位 tCOM（6 位小数）。",
    docsTableT: "当前测试网标准条款",
    docsRowNetwork: "网络",
    docsRowAsset: "资产",
    docsRowQty: "数量",
    docsRowUnit: "单价",
    docsRowFees: "预订费",
    docsRowBond: "主/备保证金",
    docsRowDeadline: "尝试时限",
    docsRowAttempts: "最多尝试",
    docsRowPenalty: "扣罚",
    docsRowTransfer: "转让",
    docsRowVerifier: "验证器",
    docsValNetwork: "X Layer 测试网 1952",
    docsValAsset: "tCOM，无价值",
    docsValQty: "20 单位",
    docsValUnit: "0.01 tCOM",
    docsValFees: "0.02 + 0.02 tCOM（买方合计 0.24）",
    docsValBond: "各 0.10 tCOM",
    docsValDeadline: "每次尝试 8 秒（不是端到端）",
    docsValAttempts: "2",
    docsValPenalty: "每次保证金失约 0.02 tCOM",
    docsValTransfer: "仅整笔剩余权益",
    docsValVerifier: "由 Commit 运营",
    cmEconT: "可领金额（链上实时）",
    providersTitle: "每个窗口背后都有交保证金的服务商",
    provPrimary: "主路",
    provBackup: "备路",
    provBond: "保证金",
    provRole1: "先应答。8 秒内不回，这次尝试记在它头上。",
    provRole2: "主路失约时接手一次。绝不静默重试。",
    provDisclosure: "两家都是项目自营、固定公开语料的 Search v1 服务。已披露，不是第三方 SaaS。",
    tlTitle: "这一笔的时间线",
    tlQuote: "从已上架服务取报价",
    tlReserve: "占用库存 · 在 1952 创建托管与保证金",
    tlPrimary: "主路执行",
    tlFailover: "注入故障 → 备路接手",
    tlFaultMissed: "第二次调用 · 故障注入未命中，主路正常应答（本次无切换）",
    tlTransfer: "剩余权益整笔转让",
    tlAfter: "新所有人执行",
    tlClose: "关闭并结算",
    tlNotRun: "未执行",
    tlRaw: "原始记录（JSON）",
    cmOwner: "所有人",
    cmRemaining: "剩余",
    cmUsed: "已用",
    cmRoute: "路由",
    cmExec: "执行 search.v1",
    cmQuery: "查询语句",
    cmRun: "发起一次尝试",
    cmReq: "请求",
    cmStatus: "状态",
    cmTransferT: "转让剩余权益",
    cmTransferP: "只能整笔转让。进行中的请求必须先排空。",
    cmBuyer: "指定买家",
    cmFreeze: "冻结并挂牌",
    cmOpenListing: "打开挂牌",
    cmClose: "关闭并结算",
    cmChainPending: "链上待处理",
    cmOpenExplorer: "在浏览器打开创建交易",
    trTag: "剩余权益整笔",
    trH1: "买下这个窗口",
    trP: "你拿到的是剩余单位、剩余窗口和 SLA，不是一个聊天机器人账号。",
    trSeller: "卖方",
    trBuyer: "指定买家",
    trRemaining: "剩余",
    trPrice: "价格",
    trStatus: "状态",
    trBuy: "以指定买家身份购买",
    trView: "查看权益",
    trDone: "已购买。所有人纪元已推进。只能从新钱包执行。",
    trLoading: "正在读取挂牌…",
    footContracts: "合约（X Layer 测试网 1952）",
    footToken: "tCOM · MockToken",
    footRegistry: "CommitmentRegistry",
    footAsp: "OKX AI 上架",
    footExplorer: "浏览器",
    footSourcify: "Sourcify",
    footLine: "tCOM 无价值。主备服务商与验证者由 Commit 运营。固定语料。不代表商业主网服务。",
    copyAddress: "复制地址",
    copy: "复制",
    copied: "已复制",
    navAgent: "Agent",
    navLab: "容量",
    evResultT: "本笔一览",
    evResultReq: "请求",
    evResultFail: "切换",
    evResultXfer: "转让",
    evResultSettle: "已结算",
    evEconThisT: "本 commitment — 费用、补偿、退款",
    evEconPrepaid: "买方预付",
    evEconPay: "付给服务商（已用 × 0.01）",
    evEconRefund: "未用托管退还",
    evEconPenalty: "故障切换扣罚给 owner",
    evEconXfer: "转让价款",
    evEconConserved: "已用 + 未用 = 原执行托管",
    evT30T: "隔离 T30 vs 共享登记合约",
    evT30Na: "记录里的 ok:false 是把钱包级 claimable 去比隔离 Hardhat 的 0.59。该检查不适用于这条共享 1952 登记合约，不代表资金丢失。",
    evCallT: "OKX AI → 链上轨迹",
    evExplorer: "浏览器",
    evWalletDetails: "钱包累计与原始 JSON",
    reserveExpiry: "报价到期",
    reserveAttempt: "8 秒是主路单次尝试超时。故障切换和结算会更久。",
    reserveTz: "时间为 UTC",
    reserveFees: "买方合计",
    agentTag: "已记录案例 · 项目方运营服务 · X Layer 测试网",
    agentH1: "一次搜索任务如何处理主服务超时",
    agentLede: "该 Agent 经已上架的 OKX AI 报价预订了搜索容量，在窗口内使用，并在 SearchNode 超过 8 秒后继续。SearchNode 与 Nova 为项目自营。本页不是研究报告。",
    agentBriefT: "示例运行摘要",
    agentTrailT: "调用链",
    agentLimit: "SearchNode 与 Nova 为项目自营、固定语料。这是一个示例 Agent，不是 Agent 市场。",
    agentBody: "下方查询与状态来自已记录运行。剩余单位可转让；未用托管在结算时退还。此处不做按时交付声明。",
    navCode: "开发文档",
    navHow: "工作原理",
    navDemo: "示例",
    sceneT: "一次搜索任务在真正调用前先预订了容量。",
    sceneP: "它先预订未来检索窗口，再在窗口内使用。查看这个示例如何处理一次主服务超时。",
    sceneSee: "先看案例，再核凭证。",
    sceneArt: "概念插画：预留的备用路径。不是精确执行拓扑。",
    runProofP: "记录关联请求与测试网交易。当前验证者由项目方运营；链上数据不能单独证明链下服务真实发生。",
    labHomeLink: "容量竞抢 — 受控占用实验",
    okxLine: "通过 OKX AI 发现与调用报价服务，在 X Layer 测试网上记录约定和结算。",
    footTech: "基于 OKX AI + X Layer 测试网",
    labTag: "容量实验",
    labH1: "容量如何避免超卖",
    labLede: "预订会锁住该窗口的主备池。后续重叠报价返回 NO_CAPACITY——执行不是开放队列。按钮会在远期 10 分钟窗口上做一次实盘 API 占用（约 120 秒过期），不上 1952 交易。",
    labRun: "跑一次实盘占用竞抢",
    labRunning: "竞抢中…",
    labA: "Agent A",
    labB: "Agent B",
    labExec: "没有预订就执行",
    labNote: "受控实验。不是付费客户。不是独立供应商网络。",
    docsAttemptNote: "8 秒是主路单次尝试期限。备用尝试、出站检查点和用户等待都可以超过 8 秒。结算不是瞬时的。",
    docsAssetNote: "登记合约接受可插拔 ERC-20 结算资产。tCOM 是当前测试代币，没有价值。",
    footAgent: "Agent 示例",
    footLab: "容量竞抢",
    footVideo: "演示视频尚未发布",
    labOversell: "超卖",
    labWindow: "实验窗口",
    ctaHow: "看这三步",
    ctaDemo: "查看案例",
    howScene: "约定，执行，核对。",
    howSub: "报价不锁容量。确认后才开始预订。",
    previewKicker: "已记录案例",
    ctaRecorded: "查看完整凭证 →",
    navProviders: "给服务商",
    kickerAsp: "ASP 未来服务预约",
    aspExpand: "ASP 即 Agent Service Provider，提供搜索、数据等能力的服务商。",
    problemT: "服务上架之后，交付才刚开始。",
    problemP: "Commit 源于创始人运营 ASP 的经历。对买方，一次超时可能打断后续任务；对供应商，没有清楚的容量约定和履约记录，也很难定位哪里需要改善。",
    buyerColT: "买方",
    buyerColP: "何时可用？能用多少？失败怎么处理？",
    provColT: "供应商",
    provColP: "应该承诺多少？哪里出现失约？如何证明自己的表现？",
    caseT: "一次搜索任务，如何处理主服务超时。",
    casePromise: "承诺",
    caseActual: "实际执行",
    caseHandling: "处理结果",
    casePromiseV: "20 次搜索 · 主路 8 秒尝试 · 带保证金备用",
    caseActualV: "执行 3 次 · 主路超时 1 次 · 备用返回",
    caseHandlingV: "剩余单位已转让并结算。未用托管已退回。",
    provSecT: "让可靠交付，成为服务商的记录。",
    provSecP: "来自一次测试网演示样本，不代表长期稳定性，也不做生产评级。",
    provHit: "主路按期有效返回",
    provBackupM: "备用恢复",
    provFailN: "双路径失败",
    provInject: "受控故障注入，不用于生产评级。",
    provCap: "声明可以实际承担的容量。",
    provSee: "看见失败发生在哪里。",
    provTune: "根据记录调整容量与配置。这是支持改进的反馈，不声称已经提高稳定性。",
    ecoT: "各层做什么",
    ecoOkx: "OKX AI — 服务发现与上架报价",
    ecoCommit: "Commit — 条款、预订、执行管理",
    ecoAsp: "接入 ASP — 实际服务",
    ecoXlayer: "X Layer — 条款哈希、资金规则与结算",
    ecoVerifier: "验证者观测链下执行并提交检查点。当前由项目方运营。",
    agentTaskT: "任务是什么",
    agentReservedT: "预订了什么",
    agentGotT: "收到了什么",
    agentHappenedT: "发生了什么",
    agentMoneyT: "钱怎么处理",
    agentNoOutput: "返回正文未落库，只保留格式校验与 response hash。本页不编造搜索摘录。",
    loadWait: "正在加载已记录案例…",
    loadFail: "暂时无法加载记录。",
    notRecorded: "未记录",
    retry: "重试",
    labDiagramT: "图解 — 本地模拟，不写数据库，不上链",
    labApiT: "受控 API 实验 — 临时占用，约 120 秒过期，无 1952 交易",
    evFeeReserveSplit: "预订费合计 {fees} tCOM，分属主备",
    evFeeIdentity: "{prepaid} = 预订 {fees} + 执行 {pay} + 未用 {refund}",
    evFeeBond: "{penalty} 补偿来自主路保证金，不是执行托管",
    evFeeXferNote: "{xfer} 转让是新买方向原 owner 的独立付款",
    evClaimableNote: "claimable 不等于已经提到钱包",
    evFirstT: "这笔约定",
    evFirstService: "约定服务",
    evFirstOp: "运营者",
    evFirstWindow: "时间窗",
    evFirstResult: "实际结果",
    evFirstMoney: "资金处理",
    evFirstVerify: "验证方式",
    serviceOp: "项目方运营 SearchNode / Nova",
    settledYes: "是",
    settledNo: "否",
    adapterNav: "接入规格",
    adapterTag: "对接形状 · 不是自助上架市场",
    adapterH1: "接入 ASP 怎样接到这条线上",
    adapterLede:
      "Commit 可以指向一个遵守该合同的服务。没有自助注册。由运营者配置 URL。占用锁的是预约窗口的准入，不是对方上游的机器或配额。",
    adapterShapeT: "执行合同",
    adapterShape:
      "POST {base}/execute，JSON 为 { attemptId, query }。须在单次尝试期限内返回（演示为 8 秒）。正文为 search.v1：schemaVersion、query、providerId、requestId、results[]（title、sourceUrl、snippet、recordId）。与演示服务一样包一层 { status, providerId, response }。",
    adapterLimitT: "Commit 实际锁什么",
    adapterLimit:
      "报价不等于预订。确认后同时占用主备窗口。没有占用则拒绝执行。保证金、托管、备用一次与结算按报价条款。Commit 不预留上游 ASP 的 CPU、配额或库存。",
    adapterNotT: "不包含",
    adapterNot:
      "没有供应商注册、没有排名、不会把任意上架 ASP 自动当备用。备用必须是明确兼容的 search.v1。交易或有副作用的接口不在范围。",
    adapterExT: "Adapter 示例",
    adapterExP: "约五十行：把只读 JSON HTTP 包成该形状。仓库路径：packages/provider-sdk/examples/readonly-http-adapter.mjs",
    caseProtocolT: "协议证据",
    caseProtocolP:
      "另一笔已记录运行：主路超时、备用、转让、结算。该笔未保存返回正文。不与交付示例拼接。",
    caseDeliveryT: "交付示例",
    caseDeliveryP:
      "正文落库之后另跑的一笔。保存的是固定公开语料上的 search.v1 命中。用了 3 个单位。该笔未能完成关闭/结算。不是实时网页搜索。不与协议 run 拼接。",
    agentCorpus: "固定公开语料 · 项目自营 SearchNode / Nova",
    agentHitSource: "来源",
    docsAdapterT: "接入规格",
    docsAdapter:
      "接入的搜索服务可实现 POST /execute + search.v1。Commit 占用是准入，不是上游产能。这是配置对接，不是自助上架。",
    docsSourceT: "代码仓库",
    docsSourcePending: "代码仓库尚未公开。",
    docsVideoT: "演示视频",
  },
} as const;

export type Copy = { [K in keyof typeof copy.en]: string };
